local UIS = game:GetService("UserInputService")
local RS = game:GetService("RunService")
local WS = game:GetService("Workspace")
local PS = game:GetService("Players")

local LPlayer = PS.LocalPlayer
local char = LPlayer.Character or LPlayer.CharacterAdded:Wait()
local root = char:WaitForChild("HumanoidRootPart")

-- Ball data
local ballRadius = 10 -- configurable live via the GUI "Ball Size" box
local baseRadius = 10 -- the radius the lattice's point count/spacing was originally tuned for;
                       -- used to scale resolution (point count), NOT part size, with ballRadius
local parts = {}
local partIndex = {}  -- [BasePart] = index into ballParts/parts. Also doubles as "is this one of MY fragments".
local ballParts = {}
local active = false
local conn = nil
local ballPos = Vector3.zero
local ballVelocity = Vector3.zero
local visualRot = CFrame.identity
local lastBallPos = Vector3.zero

-- Movement
local speed = 30          -- configurable live via the GUI "Ball Speed" box
local accelRate = 8
local dirs = {Forward = 0, Backward = 0, Left = 0, Right = 0}
local rotL, rotR = false, false
local kbd = false
local velConn = nil

-- Cursor Stretch: click-and-hold on the ball to pull a point outward, following your cursor
local stretchMode = false
local stretchHeld = false
local stretchDepth = 1.4 -- studs of outward pull per unit of stretch strength

--=========================================================================
-- TOUCH DETECTOR: per-point localized squish system.
-- Instead of one "squish axis" for the whole ball, every fragment of the
-- ball is checked individually via a spatial overlap query (GetPartsInPart),
-- which is far more reliable than the legacy GetTouchingParts/Touched event
-- system for parts whose position is set directly via CFrame every frame
-- rather than moved by the physics engine. Any fragment that's actually
-- overlapping something dents INWARD right at that spot, with a soft
-- falloff to nearby fragments and a small outward rim bulge for volume.
-- Ground landings, wall/object contact, fast-motion squash, the manual
-- squish buttons, AND cursor stretch are all just different callers of the
-- same applyLocalDent()/applyLocalStretch() functions below.
--=========================================================================
local squishIntensity = 1       -- 0 = rigid, 1 = default, up to 3 = extremely squishy (scales strength + depth)
local dentRadius = 9            -- studs; how far a dent's influence spreads across the ball's surface
local dentDepth = 0.6           -- studs of inward dent per unit of squish strength (strength maxes at 10)
local bulgeDepth = 0.25         -- studs of outward rim bulge per unit of squish strength
local squishSpringSpeed = 6     -- how fast the visible dent/stretch springs toward its target each frame
local squishDecay = 3           -- how fast a target fades on its own once nothing is re-triggering it

local localDentTarget, localDentAmount = {}, {}
local localBulgeTarget, localBulgeAmount = {}, {}
local localStretchTarget, localStretchAmount = {}, {}
local wasTouchingFragment = {}  -- per-fragment edge-trigger so resting contact doesn't stay pinned forever
local wasGrounded = false

-- Updates ballRadius and keeps dentRadius proportional to it (dentRadius was tuned as
-- 0.9x a 10-stud ball, so we preserve that ratio at any size). Clamped to a sane range.
local function applyRadius(r)
    ballRadius = math.clamp(r, 3, 30)
    dentRadius = ballRadius * 0.9
end

-- Physics
local gravity = Vector3.new(0, -196.2, 0)
local terminalVelocity = 150
local physicsDrag = 2

local plateBounds = nil

local rayParams = RaycastParams.new()
rayParams.FilterType = Enum.RaycastFilterType.Exclude
rayParams.FilterDescendantsInstances = {}

local overlapParams = OverlapParams.new()
overlapParams.FilterType = Enum.RaycastFilterType.Exclude
overlapParams.FilterDescendantsInstances = {}
-- FIX (squish hardening): force this false so a non-collidable fragment (CanCollide = false,
-- since we drive position via CFrame every frame) still registers overlaps against solid
-- geometry like the ground/walls. If this were ever true, GetPartsInPart could silently
-- return zero results for every fragment and touch-based squish would look completely dead.
overlapParams.RespectCanCollide = false

local stretchRayParams = RaycastParams.new()
stretchRayParams.FilterType = Enum.RaycastFilterType.Include
stretchRayParams.FilterDescendantsInstances = {}

local ballDirs = {} -- unit-sphere direction for each lattice point; only regenerated by
                     -- rebuildBall(), so the point count only ever changes on a full rebuild

local function rebuildBall()
    ballParts = {}
    ballDirs = {}
    localDentTarget, localDentAmount = {}, {}
    localBulgeTarget, localBulgeAmount = {}, {}
    localStretchTarget, localStretchAmount = {}, {}
    wasTouchingFragment = {}

    -- Point count scales with radius instead of block Size scaling with radius: surface area
    -- grows with r^2, so we scale linear resolution with r to keep spacing between grabbed
    -- blocks roughly constant. This only works as well as how many real blocks are sitting on
    -- your plate — a bigger ball needs proportionally more placed blocks to stay gap-free;
    -- past that it'll just leave some lattice points unfilled (same as running low on parts).
    local resolution = math.clamp(math.floor(10 * (ballRadius / baseRadius) + 0.5), 4, 20)
    for lat = 0, resolution do
        local theta = (math.pi * lat) / resolution
        local sinTheta = math.sin(theta)
        local cosTheta = math.cos(theta)
        local actualPoints = math.max(3, math.floor(resolution * 2 * sinTheta))
        for lon = 0, actualPoints do
            local phi = (2 * math.pi * lon) / actualPoints
            local dir = Vector3.new(
                sinTheta * math.cos(phi),
                cosTheta,
                sinTheta * math.sin(phi)
            )
            table.insert(ballDirs, dir)
            table.insert(ballParts, dir * ballRadius)
            local idx = #ballParts
            localDentTarget[idx] = 0
            localDentAmount[idx] = 0
            localBulgeTarget[idx] = 0
            localBulgeAmount[idx] = 0
            localStretchTarget[idx] = 0
            localStretchAmount[idx] = 0
            wasTouchingFragment[idx] = false
        end
    end
end
rebuildBall()

-- Rescales the EXISTING lattice to the current ballRadius without touching point count, so it's
-- safe to call on a live, already-built ball (fragment<->index bindings stay valid — same number
-- of points, just spaced differently). Use this for live size tweaks; use rebuildBall() only when
-- actually regathering parts (BUILD BALL), since that's the only time point count may change.
local function rescaleBallRadius()
    for j = 1, #ballDirs do
        ballParts[j] = ballDirs[j] * ballRadius
    end
end

-- Applies a dent centered at `centerLocal` (a point in the ball's own local space, e.g. one
-- of the ballParts entries) with the given `strength` (0-10ish). Every nearby point gets a
-- dent contribution based on distance falloff, plus a smaller rim-bulge contribution.
local function applyLocalDent(centerLocal, strength)
    for j = 1, #ballParts do
        local dist = (ballParts[j] - centerLocal).Magnitude
        if dist < dentRadius then
            local r = dist / dentRadius
            local dentFalloff = (1 - r) * (1 - r)                                  -- peaks at the contact point
            local bulgeFalloff = math.max(0, 1 - math.abs(r - 0.75) / 0.35) * 0.4  -- small ring around r≈0.75

            local dentVal = strength * dentFalloff
            local bulgeVal = strength * bulgeFalloff
            if dentVal > localDentTarget[j] then localDentTarget[j] = dentVal end
            if bulgeVal > localBulgeTarget[j] then localBulgeTarget[j] = bulgeVal end
        end
    end
end

-- Same falloff shape as applyLocalDent, but pulls points OUTWARD instead of in. Used for the
-- cursor-stretch feature: grab a point on the ball's surface and drag it out like taffy.
local function applyLocalStretch(centerLocal, strength)
    for j = 1, #ballParts do
        local dist = (ballParts[j] - centerLocal).Magnitude
        if dist < dentRadius then
            local r = dist / dentRadius
            local falloff = (1 - r) * (1 - r)
            local val = strength * falloff
            if val > localStretchTarget[j] then localStretchTarget[j] = val end
        end
    end
end

local function isPartSafe(p)
    if p.Anchored then return false end
    for _, plr in pairs(PS:GetPlayers()) do
        if plr.Character and p:IsDescendantOf(plr.Character) then return false end
    end
    if next(p:GetJoints()) ~= nil then return false end
    for _, c in pairs(p:GetChildren()) do
        if c:IsA("JointInstance") or c:IsA("Constraint") then return false end
    end
    return true
end

local function getMyPlate()
    local Plates = WS:FindFirstChild("Plates")
    if not Plates then return nil end
    for _, plate in pairs(Plates:GetChildren()) do
        local owner = plate:FindFirstChild("Owner")
        if owner and owner.Value == LPlayer then return plate end
    end
    return nil
end

local function findMyPlateBounds(plate)
    local platePart = plate and plate:FindFirstChild("Plate")
    if not (platePart and platePart:IsA("BasePart")) then return nil end
    local size = platePart.Size
    local pos = platePart.Position
    return {
        minX = pos.X - size.X / 2,
        maxX = pos.X + size.X / 2,
        minZ = pos.Z - size.Z / 2,
        maxZ = pos.Z + size.Z / 2,
        center = pos
    }
end

local function clampToPlate(pos)
    if not plateBounds then return pos end
    local radius = ballRadius + 2
    return Vector3.new(
        math.clamp(pos.X, plateBounds.minX + radius, plateBounds.maxX - radius),
        pos.Y,
        math.clamp(pos.Z, plateBounds.minZ + radius, plateBounds.maxZ - radius)
    )
end

local function getGroundHeight(pos)
    local hit = WS:Raycast(pos + Vector3.new(0, 50, 0), Vector3.new(0, -300, 0), rayParams)
    if hit then return hit.Position.Y end
    return pos.Y - 50
end

-- GUI setup
local sg = Instance.new("ScreenGui", LPlayer:WaitForChild("PlayerGui"))
sg.Name = "NeedohBall"
sg.ResetOnSpawn = false

local mf = Instance.new("Frame", sg)
mf.Size = UDim2.new(0, 280, 0, 530)
mf.Position = UDim2.new(0.5, -140, 0.5, -265)
mf.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
mf.BorderSizePixel = 0
Instance.new("UICorner", mf).CornerRadius = UDim.new(0, 10)

local function btn(t, x, y, w, h, c)
    local b = Instance.new("TextButton", mf)
    b.Size = UDim2.new(0, w, 0, h)
    b.Position = UDim2.new(0, x, 0, y)
    b.BackgroundColor3 = c
    b.Text = t
    b.Font = Enum.Font.GothamBold
    b.TextSize = 10
    b.TextColor3 = Color3.fromRGB(255, 255, 255)
    Instance.new("UICorner", b).CornerRadius = UDim.new(0, 5)
    return b
end

local function label(t, x, y, w, h)
    local l = Instance.new("TextLabel", mf)
    l.Size = UDim2.new(0, w, 0, h)
    l.Position = UDim2.new(0, x, 0, y)
    l.BackgroundTransparency = 1
    l.Text = t
    l.TextColor3 = Color3.fromRGB(255, 255, 255)
    l.TextSize = 10
    l.Font = Enum.Font.Gotham
    return l
end

local tb = btn("NEEDOH BALL (drag)", 0, 0, 280, 26, Color3.fromRGB(25, 25, 25))
tb.AutoButtonColor = false
tb.TextColor3 = Color3.fromRGB(255, 100, 100)
tb.TextSize = 12

local guiDrag, guiStart, guiPos = false, nil, nil
tb.InputBegan:Connect(function(i)
    if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then
        guiDrag = true
        guiStart = i.Position
        guiPos = mf.Position
    end
end)
UIS.InputChanged:Connect(function(i)
    if not guiDrag then return end
    if i.UserInputType == Enum.UserInputType.MouseMovement or i.UserInputType == Enum.UserInputType.Touch then
        local d = i.Position - guiStart
        mf.Position = UDim2.new(guiPos.X.Scale, guiPos.X.Offset + d.X, guiPos.Y.Scale, guiPos.Y.Offset + d.Y)
    end
end)
UIS.InputEnded:Connect(function(i)
    if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then
        guiDrag = false
    end
end)

local stat = label("Off", 0, 500, 280, 18)
stat.TextColor3 = Color3.fromRGB(180, 180, 180)

label("Squish Intensity:", 10, 290, 100, 18).TextSize = 9
local squishBox = Instance.new("TextBox", mf)
squishBox.Size = UDim2.new(0, 50, 0, 20)
squishBox.Position = UDim2.new(0, 110, 0, 289)
squishBox.Text = "1"
squishBox.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
squishBox.TextColor3 = Color3.fromRGB(255, 255, 255)
squishBox.Font = Enum.Font.Gotham
squishBox.TextSize = 10
squishBox.BorderSizePixel = 0

btn("SET", 170, 288, 50, 22, Color3.fromRGB(150, 100, 255)).MouseButton1Click:Connect(function()
    local n = tonumber(squishBox.Text)
    if n then
        squishIntensity = math.clamp(n, 0, 3)
    end
end)

label("Velocity Power:", 10, 320, 100, 18).TextSize = 9
local velBox = Instance.new("TextBox", mf)
velBox.Size = UDim2.new(0, 50, 0, 20)
velBox.Position = UDim2.new(0, 110, 0, 319)
velBox.Text = "50"
velBox.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
velBox.TextColor3 = Color3.fromRGB(255, 255, 255)
velBox.Font = Enum.Font.Gotham
velBox.TextSize = 10
velBox.BorderSizePixel = 0

local velocityPower = 50
btn("SET", 170, 318, 50, 22, Color3.fromRGB(150, 100, 255)).MouseButton1Click:Connect(function()
    local n = tonumber(velBox.Text)
    if n then
        velocityPower = n
    end
end)

label("Ball Speed:", 10, 350, 100, 18).TextSize = 9
local speedBox = Instance.new("TextBox", mf)
speedBox.Size = UDim2.new(0, 50, 0, 20)
speedBox.Position = UDim2.new(0, 110, 0, 349)
speedBox.Text = tostring(speed)
speedBox.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
speedBox.TextColor3 = Color3.fromRGB(255, 255, 255)
speedBox.Font = Enum.Font.Gotham
speedBox.TextSize = 10
speedBox.BorderSizePixel = 0

btn("SET", 170, 348, 50, 22, Color3.fromRGB(150, 100, 255)).MouseButton1Click:Connect(function()
    local n = tonumber(speedBox.Text)
    if n then
        speed = math.max(0, n)
    end
end)

label("Gravity:", 10, 380, 100, 18).TextSize = 9
local gravBox = Instance.new("TextBox", mf)
gravBox.Size = UDim2.new(0, 50, 0, 20)
gravBox.Position = UDim2.new(0, 110, 0, 379)
gravBox.Text = "196.2"
gravBox.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
gravBox.TextColor3 = Color3.fromRGB(255, 255, 255)
gravBox.Font = Enum.Font.Gotham
gravBox.TextSize = 10
gravBox.BorderSizePixel = 0

-- FIX: this SET button used to sit at (170, 348) — the exact same spot as the Ball Speed
-- SET button above. Being created later, it rendered on top and swallowed every click there,
-- so "setting speed" was actually always setting gravity instead. Moved to align with its
-- own row (gravBox is at y=379) so both buttons are independently clickable.
btn("SET", 170, 378, 50, 22, Color3.fromRGB(150, 100, 255)).MouseButton1Click:Connect(function()
    local n = tonumber(gravBox.Text)
    if n then
        gravity = Vector3.new(0, -math.abs(n), 0) -- always downward no matter what sign was typed
    end
end)

label("Ball Size:", 10, 410, 100, 18).TextSize = 9
local sizeBox = Instance.new("TextBox", mf)
sizeBox.Size = UDim2.new(0, 50, 0, 20)
sizeBox.Position = UDim2.new(0, 110, 0, 409)
sizeBox.Text = tostring(ballRadius)
sizeBox.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
sizeBox.TextColor3 = Color3.fromRGB(255, 255, 255)
sizeBox.Font = Enum.Font.Gotham
sizeBox.TextSize = 10
sizeBox.BorderSizePixel = 0

btn("SET", 170, 408, 50, 22, Color3.fromRGB(150, 100, 255)).MouseButton1Click:Connect(function()
    local n = tonumber(sizeBox.Text)
    if n then
        applyRadius(n)
        sizeBox.Text = tostring(ballRadius) -- reflect the clamp if the typed value was out of range
        if active then
            -- Live tweak: keep the SAME point count/fragment bindings, just respace them at the
            -- new radius. Getting denser coverage (more blocks) at a bigger size requires
            -- regathering parts, which only happens via BUILD BALL — click it again after
            -- placing enough blocks to fill out the new size gap-free.
            rescaleBallRadius()
            posBall()
        end
    end
end)

-- Manual squish buttons now just call the SAME Touch Detector dent function at a fixed side point
btn("SQUISH LEFT", 10, 440, 125, 28, Color3.fromRGB(255, 150, 50)).MouseButton1Click:Connect(function()
    if not active then return end
    applyLocalDent(Vector3.new(-ballRadius, 0, 0), math.min(10, 8 * squishIntensity))
end)

btn("SQUISH RIGHT", 145, 440, 125, 28, Color3.fromRGB(255, 200, 50)).MouseButton1Click:Connect(function()
    if not active then return end
    applyLocalDent(Vector3.new(ballRadius, 0, 0), math.min(10, 8 * squishIntensity))
end)

-- Cursor Stretch: toggle on, then click-and-hold anywhere on the ball to grab and pull that
-- point outward, following your cursor while held. Release to let it spring back.
local stretchBtn = btn("STRETCH MODE: OFF", 10, 472, 260, 26, Color3.fromRGB(100, 100, 100))
stretchBtn.MouseButton1Click:Connect(function()
    stretchMode = not stretchMode
    if stretchMode then
        stretchBtn.Text = "STRETCH MODE: ON (click + drag ball)"
        stretchBtn.BackgroundColor3 = Color3.fromRGB(80, 160, 255)
    else
        stretchBtn.Text = "STRETCH MODE: OFF"
        stretchBtn.BackgroundColor3 = Color3.fromRGB(100, 100, 100)
        stretchHeld = false
    end
end)

UIS.InputBegan:Connect(function(i, gpe)
    if gpe or not stretchMode then return end
    if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then
        stretchHeld = true
    end
end)
UIS.InputEnded:Connect(function(i)
    if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then
        stretchHeld = false
    end
end)

local buildDebounce = false

local function teardownBall()
    active = false
    if conn then
        conn:Disconnect()
        conn = nil
    end
    for _, b in pairs(parts) do
        if b and b.Parent then
            b.Velocity = Vector3.zero
            b.CanCollide = true
            for _, v in pairs(b:GetChildren()) do
                if v:IsA("BodyMover") then
                    v:Destroy()
                end
            end
        end
    end
    table.clear(parts)
    table.clear(partIndex)
    rayParams.FilterDescendantsInstances = {}
    overlapParams.FilterDescendantsInstances = {}
    stretchRayParams.FilterDescendantsInstances = {}
end

local posBall

btn("BUILD BALL", 10, 32, 260, 28, Color3.fromRGB(50, 200, 50)).MouseButton1Click:Connect(function()
    if buildDebounce then return end
    buildDebounce = true
    teardownBall()

    local myPlate = getMyPlate()
    if not myPlate then
        stat.Text = "No plate found"
        buildDebounce = false
        return
    end
    plateBounds = findMyPlateBounds(myPlate)
    if not plateBounds then
        stat.Text = "No plate part"
        buildDebounce = false
        return
    end

    local activeParts = myPlate:FindFirstChild("ActiveParts")
    if not activeParts then
        stat.Text = "No ActiveParts"
        buildDebounce = false
        return
    end

    rebuildBall()
    local fp = {}
    for _, p in pairs(activeParts:GetDescendants()) do
        if p:IsA("BasePart") and isPartSafe(p) and p.Transparency < 0.5 then
            table.insert(fp, p)
        end
    end
    if #fp == 0 then
        stat.Text = "No parts"
        buildDebounce = false
        return
    end

    table.sort(fp, function(a, b)
        return (a.Position - root.Position).Magnitude < (b.Position - root.Position).Magnitude
    end)
    for i = 1, math.min(#ballParts, #fp) do
        local p = fp[i]
        table.insert(parts, p)
        partIndex[p] = i
    end
    rayParams.FilterDescendantsInstances = parts
    overlapParams.FilterDescendantsInstances = parts
    stretchRayParams.FilterDescendantsInstances = parts

    ballPos = plateBounds.center + Vector3.new(0, ballRadius * 2, 0)
    lastBallPos = ballPos
    visualRot = CFrame.identity
    ballVelocity = Vector3.zero
    wasGrounded = false

    posBall()
    active = true
    stat.Text = "Ball: " .. #parts .. " parts"

    conn = RS.Heartbeat:Connect(function(dt)
        if not active then return end

        -- Movement: accelerate TOWARD a target horizontal speed, scaled by dt
        local moveWorld = Vector3.new(dirs.Right - dirs.Left, 0, dirs.Forward - dirs.Backward)
        if moveWorld.Magnitude > 0 then
            local desired = moveWorld.Unit * speed
            local blend = math.min(1, dt * accelRate)
            ballVelocity = Vector3.new(
                ballVelocity.X + (desired.X - ballVelocity.X) * blend,
                ballVelocity.Y,
                ballVelocity.Z + (desired.Z - ballVelocity.Z) * blend
            )
        end

        if rotL then
            visualRot = visualRot * CFrame.Angles(0, math.rad(90) * dt, 0)
        end
        if rotR then
            visualRot = visualRot * CFrame.Angles(0, -math.rad(90) * dt, 0)
        end

        ballVelocity = ballVelocity + gravity * dt
        if ballVelocity.Y < -terminalVelocity then
            ballVelocity = Vector3.new(ballVelocity.X, -terminalVelocity, ballVelocity.Z)
        end

        ballPos = ballPos + ballVelocity * dt

        local clamped = clampToPlate(ballPos)
        if clamped ~= ballPos then
            ballPos = clamped
            ballVelocity = Vector3.new(0, ballVelocity.Y, 0)
        end

        -- Ground contact: snap to floor, dent the bottom ONCE per landing (edge-triggered)
        local groundY = getGroundHeight(ballPos)
        local grounded = ballPos.Y - ballRadius <= groundY
        if grounded then
            ballPos = Vector3.new(ballPos.X, groundY + ballRadius, ballPos.Z)
            if ballVelocity.Y < -1 and not wasGrounded then
                local strength = math.min(10, math.max(4, math.abs(ballVelocity.Y) * 0.15) * squishIntensity)
                -- FIX: (0,-radius,0) was a fixed LOCAL point, which only means "world down" while
                -- the ball hasn't rotated. As soon as it rolls (which happens constantly while
                -- moving), local down drifts away from world down and the dent lands on whatever
                -- side used to be the bottom instead of the side that actually hit the ground.
                -- Convert world-down into the ball's current local/object space first.
                local downLocal = visualRot:VectorToObjectSpace(Vector3.new(0, -1, 0)) * ballRadius
                applyLocalDent(downLocal, strength)
            end
            if ballVelocity.Y < 0 then
                ballVelocity = Vector3.new(ballVelocity.X * 0.3, 0, ballVelocity.Z * 0.3)
            end
        end
        wasGrounded = grounded

        --=== TOUCH DETECTOR: check every fragment individually via a spatial overlap query
        -- (GetPartsInPart), which reads the fragment's actual current geometry directly and
        -- doesn't depend on the legacy Touched-event system keeping up with CFrame teleports ===--
        for i, b in ipairs(parts) do
            local isTouchingNow = false
            local touchImpact = 0
            if b and b.Parent then
                local overlaps = WS:GetPartsInPart(b, overlapParams)
                if #overlaps > 0 then
                    isTouchingNow = true
                    local outwardWorld = visualRot:VectorToWorldSpace(ballParts[i].Unit)
                    touchImpact = math.abs(ballVelocity:Dot(outwardWorld))
                end
            end
            if isTouchingNow and not wasTouchingFragment[i] then
                local strength = math.min(10, math.max(4, touchImpact * 0.15) * squishIntensity)
                applyLocalDent(ballParts[i], strength)
            end
            wasTouchingFragment[i] = isTouchingNow
        end

        -- Fast-motion squash: dent the LEADING edge (the point on the sphere facing the
        -- direction of travel), same detector, no separate system needed
        local velMag = ballVelocity.Magnitude
        if velMag > 20 then
            local travelDirWorld = ballVelocity.Unit
            local leadLocal = visualRot:VectorToObjectSpace(travelDirWorld) * ballRadius
            applyLocalDent(leadLocal, math.min(10, velMag * 0.08 * squishIntensity))
        end

        -- Cursor Stretch: while held, raycast from the camera through the mouse position,
        -- restricted to ONLY this ball's fragments (stretchRayParams Include filter). Whichever
        -- fragment is under the cursor gets pulled outward, following the cursor as it moves.
        if stretchMode and stretchHeld then
            local camera = WS.CurrentCamera
            local mouseLoc = UIS:GetMouseLocation()
            if camera then
                local ray = camera:ScreenPointToRay(mouseLoc.X, mouseLoc.Y)
                local hit = WS:Raycast(ray.Origin, ray.Direction * 1000, stretchRayParams)
                if hit and hit.Instance and partIndex[hit.Instance] then
                    local hitIndex = partIndex[hit.Instance]
                    applyLocalStretch(ballParts[hitIndex], math.min(10, 8 * squishIntensity))
                end
            end
        end

        -- Rolling rotation (horizontal only) -- purely visual, never touches ballVelocity/movement
        local deltaPos = ballPos - lastBallPos
        lastBallPos = ballPos
        local horizontalDelta = Vector3.new(deltaPos.X, 0, deltaPos.Z)
        if horizontalDelta.Magnitude > 0.001 then
            local rollAngle = horizontalDelta.Magnitude / 10
            local rollAxis = Vector3.new(0, 1, 0):Cross(horizontalDelta.Unit)
            if rollAxis.Magnitude > 0.001 then
                visualRot = visualRot * CFrame.fromAxisAngle(rollAxis.Unit, rollAngle)
            end
        end

        -- Spring + decay every point's dent/bulge/stretch toward its target
        for i = 1, #ballParts do
            localDentTarget[i] = localDentTarget[i] * math.max(0, 1 - dt * squishDecay)
            localDentAmount[i] = localDentAmount[i] + (localDentTarget[i] - localDentAmount[i]) * dt * squishSpringSpeed
            if localDentAmount[i] < 0.05 then
                localDentAmount[i] = 0
                localDentTarget[i] = 0
            end

            localBulgeTarget[i] = localBulgeTarget[i] * math.max(0, 1 - dt * squishDecay)
            localBulgeAmount[i] = localBulgeAmount[i] + (localBulgeTarget[i] - localBulgeAmount[i]) * dt * squishSpringSpeed
            if localBulgeAmount[i] < 0.05 then
                localBulgeAmount[i] = 0
                localBulgeTarget[i] = 0
            end

            -- Stretch decays slower than dent/bulge by default so a "grabbed" point holds its
            -- shape for a moment after release instead of snapping back instantly
            localStretchTarget[i] = localStretchTarget[i] * math.max(0, 1 - dt * (squishDecay * 0.5))
            localStretchAmount[i] = localStretchAmount[i] + (localStretchTarget[i] - localStretchAmount[i]) * dt * squishSpringSpeed
            if localStretchAmount[i] < 0.05 then
                localStretchAmount[i] = 0
                localStretchTarget[i] = 0
            end
        end

        ballVelocity = Vector3.new(
            ballVelocity.X * (1 - dt * physicsDrag),
            ballVelocity.Y,
            ballVelocity.Z * (1 - dt * physicsDrag)
        )

        posBall()
    end)

    buildDebounce = false
end)

btn("ADD VELOCITY", 10, 98, 125, 28, Color3.fromRGB(255, 150, 50)).MouseButton1Click:Connect(function()
    if not active then return end
    local horiz = Vector3.new(ballVelocity.X, 0, ballVelocity.Z)
    local dir = horiz.Magnitude > 0.5 and horiz.Unit or Vector3.new(0, 0, -1)
    ballVelocity = ballVelocity + dir * velocityPower
end)

btn("RESET VELOCITY", 145, 98, 125, 28, Color3.fromRGB(255, 200, 50)).MouseButton1Click:Connect(function()
    ballVelocity = Vector3.zero
end)

btn("DESTROY", 10, 132, 260, 26, Color3.fromRGB(255, 80, 80)).MouseButton1Click:Connect(function()
    teardownBall()
    stat.Text = "Off"
end)

local kbdBtn = btn("KEYBOARD: OFF", 10, 164, 260, 26, Color3.fromRGB(100, 100, 100))
kbdBtn.MouseButton1Click:Connect(function()
    kbd = not kbd
    if kbd then
        kbdBtn.Text = "KEYBOARD: ON (WASD/Z/X)"
        kbdBtn.BackgroundColor3 = Color3.fromRGB(50, 200, 50)
    else
        kbdBtn.Text = "KEYBOARD: OFF"
        kbdBtn.BackgroundColor3 = Color3.fromRGB(100, 100, 100)
        for k in pairs(dirs) do
            dirs[k] = 0
        end
        rotL, rotR = false, false
        if velConn then
            velConn:Disconnect()
            velConn = nil
        end
        local endTime = tick() + 1
        velConn = RS.Heartbeat:Connect(function()
            if tick() >= endTime then
                if velConn then
                    velConn:Disconnect()
                    velConn = nil
                end
                return
            end
            if root and root.Parent then
                root.Velocity = Vector3.zero
                root.RotVelocity = Vector3.zero
            end
        end)
    end
end)

local function dirBtn(t, x, y, c, dir)
    local b = btn(t, x, y, 40, 28, c)
    b.TextSize = 12
    b.MouseButton1Down:Connect(function()
        dirs[dir] = 1
    end)
    b.MouseButton1Up:Connect(function()
        dirs[dir] = 0
    end)
    b.MouseLeave:Connect(function()
        dirs[dir] = 0
    end)
end
dirBtn("W", 110, 196, Color3.fromRGB(255, 200, 50), "Forward")
dirBtn("S", 110, 228, Color3.fromRGB(255, 200, 50), "Backward")
dirBtn("A", 65, 212, Color3.fromRGB(255, 100, 100), "Left")
dirBtn("D", 155, 212, Color3.fromRGB(255, 100, 100), "Right")

local zBtn = btn("Z", 15, 196, 40, 28, Color3.fromRGB(200, 150, 255))
zBtn.MouseButton1Down:Connect(function()
    rotL = true
end)
zBtn.MouseButton1Up:Connect(function()
    rotL = false
end)
zBtn.MouseLeave:Connect(function()
    rotL = false
end)

local xBtn = btn("X", 15, 228, 40, 28, Color3.fromRGB(200, 150, 255))
xBtn.MouseButton1Down:Connect(function()
    rotR = true
end)
xBtn.MouseButton1Up:Connect(function()
    rotR = false
end)
xBtn.MouseLeave:Connect(function()
    rotR = false
end)

UIS.InputBegan:Connect(function(i, gpe)
    if gpe or not kbd then return end
    if i.KeyCode == Enum.KeyCode.W then
        dirs.Forward = 1
    elseif i.KeyCode == Enum.KeyCode.S then
        dirs.Backward = 1
    elseif i.KeyCode == Enum.KeyCode.A then
        dirs.Left = 1
    elseif i.KeyCode == Enum.KeyCode.D then
        dirs.Right = 1
    elseif i.KeyCode == Enum.KeyCode.Z then
        rotL = true
    elseif i.KeyCode == Enum.KeyCode.X then
        rotR = true
    end
end)
UIS.InputEnded:Connect(function(i, gpe)
    if gpe or not kbd then return end
    if i.KeyCode == Enum.KeyCode.W then
        dirs.Forward = 0
    elseif i.KeyCode == Enum.KeyCode.S then
        dirs.Backward = 0
    elseif i.KeyCode == Enum.KeyCode.A then
        dirs.Left = 0
    elseif i.KeyCode == Enum.KeyCode.D then
        dirs.Right = 0
    elseif i.KeyCode == Enum.KeyCode.Z then
        rotL = false
    elseif i.KeyCode == Enum.KeyCode.X then
        rotR = false
    end
end)

posBall = function()
    if not active then return end
    for i = 1, #parts do
        local b = parts[i]
        local d = ballParts[i]
        if b and b.Parent and d then
            for _, v in pairs(b:GetChildren()) do
                if v:IsA("BodyMover") then
                    v:Destroy()
                end
            end
            b.RotVelocity = Vector3.zero
            b.CanCollide = false
            b.Anchored = false

            -- Net radial offset: dent pulls the point IN toward center, bulge pushes it OUT,
            -- and (FIX) stretch now also pushes it OUT — this was computed every frame but
            -- never actually applied to fragment positions before, so cursor-stretch had zero
            -- visible effect no matter how hard you pulled.
            local netRadial = (localBulgeAmount[i] * bulgeDepth)
                - (localDentAmount[i] * dentDepth)
                + (localStretchAmount[i] * stretchDepth)
            local pos = d + d.Unit * netRadial

            b.CFrame = CFrame.new(ballPos) * visualRot * CFrame.new(pos)
        end
    end
end

LPlayer.CharacterAdded:Connect(function(c)
    char = c
    root = c:WaitForChild("HumanoidRootPart")
    sg.Parent = LPlayer:WaitForChild("PlayerGui")
    teardownBall()
end)
